name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, raspberrypi]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Raspberry Pi
        run: |
          mkdir -p /home/pi/ushbub && cd /home/piushbub && git pull origin main && docker compose up -d --build
